[build]
  # Build command untuk copy files ke public
  command = "npm run build"
  
  # Directory yang akan di-deploy (public directory)
  publish = "public"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# API redirects ke single function (must be first)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# Redirect rules untuk SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers untuk security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers khusus untuk API
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
